steps:
# Step 1: Build and deploy Cloud Functions
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'cloud-functions'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'cloud-functions'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'noorHrApi'
  - '--source=./cloud-functions'
  - '--trigger-http'
  - '--runtime=nodejs20'
  - '--region=us-central1'
  - '--allow-unauthenticated'
  - '--set-secrets=API_KEY=${_API_KEY_SECRET_VERSION}'

# Step 2: Build the frontend container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/noor-hr-frontend:$COMMIT_SHA', '.']
  
# Step 3: Push the container image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/noor-hr-frontend:$COMMIT_SHA']

# Step 4: Deploy the container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'noor-hr-frontend'
  - '--image=gcr.io/$PROJECT_ID/noor-hr-frontend:$COMMIT_SHA'
  - '--platform=managed'
  - '--region=us-central1' 
  - '--allow-unauthenticated'
  - '--quiet'

images:
- 'gcr.io/$PROJECT_ID/noor-hr-frontend:$COMMIT_SHA'
